#ifndef __HTML_DATA_H
#define __HTML_DATA_H

#include "sys.h"

// 配网页面的HTML代码
const char* wifi_config_html = "<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>智能机器人WiFi配置</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            background-color: #f5f5f5;\n"
"            color: #333;\n"
"        }\n"
"        .container {\n"
"            max-width: 400px;\n"
"            margin: 0 auto;\n"
"            padding: 20px;\n"
"        }\n"
"        .header {\n"
"            text-align: center;\n"
"            padding: 20px 0;\n"
"            background-color: #0078d7;\n"
"            color: white;\n"
"            border-radius: 5px 5px 0 0;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        .form-container {\n"
"            background-color: white;\n"
"            border-radius: 5px;\n"
"            padding: 20px;\n"
"            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n"
"        }\n"
"        .form-group {\n"
"            margin-bottom: 15px;\n"
"        }\n"
"        label {\n"
"            display: block;\n"
"            margin-bottom: 5px;\n"
"            font-weight: bold;\n"
"        }\n"
"        input[type=\"text\"],\n"
"        input[type=\"password\"] {\n"
"            width: 100%;\n"
"            padding: 10px;\n"
"            border: 1px solid #ddd;\n"
"            border-radius: 4px;\n"
"            box-sizing: border-box;\n"
"        }\n"
"        button {\n"
"            background-color: #0078d7;\n"
"            color: white;\n"
"            border: none;\n"
"            padding: 12px 20px;\n"
"            border-radius: 4px;\n"
"            cursor: pointer;\n"
"            width: 100%;\n"
"            font-size: 16px;\n"
"            margin-top: 10px;\n"
"        }\n"
"        button:hover {\n"
"            background-color: #0056b3;\n"
"        }\n"
"        .status {\n"
"            margin-top: 20px;\n"
"            padding: 10px;\n"
"            border-radius: 4px;\n"
"            text-align: center;\n"
"            display: none;\n"
"        }\n"
"        .status.success {\n"
"            background-color: #d4edda;\n"
"            color: #155724;\n"
"            display: block;\n"
"        }\n"
"        .status.error {\n"
"            background-color: #f8d7da;\n"
"            color: #721c24;\n"
"            display: block;\n"
"        }\n"
"        .status.connecting {\n"
"            background-color: #fff3cd;\n"
"            color: #856404;\n"
"            display: block;\n"
"        }\n"
"        .footer {\n"
"            text-align: center;\n"
"            margin-top: 20px;\n"
"            color: #666;\n"
"            font-size: 12px;\n"
"        }\n"
"        .network-list {\n"
"            max-height: 200px;\n"
"            overflow-y: auto;\n"
"            margin-bottom: 15px;\n"
"            border: 1px solid #ddd;\n"
"            border-radius: 4px;\n"
"        }\n"
"        .network-item {\n"
"            padding: 10px;\n"
"            border-bottom: 1px solid #eee;\n"
"            cursor: pointer;\n"
"        }\n"
"        .network-item:hover {\n"
"            background-color: #f5f5f5;\n"
"        }\n"
"        .network-item:last-child {\n"
"            border-bottom: none;\n"
"        }\n"
"        .signal-strength {\n"
"            float: right;\n"
"        }\n"
"        @media (max-width: 480px) {\n"
"            .container {\n"
"                padding: 10px;\n"
"            }\n"
"            .header {\n"
"                padding: 15px 0;\n"
"            }\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <div class=\"header\">\n"
"            <h1>智能机器人WiFi配置</h1>\n"
"        </div>\n"
"        <div class=\"form-container\">\n"
"            <div id=\"networkList\" class=\"network-list\">\n"
"                <!-- 网络列表会通过JavaScript动态添加 -->\n"
"                <div class=\"network-item\">正在扫描可用网络...</div>\n"
"            </div>\n"
"            <form id=\"wifiForm\">\n"
"                <div class=\"form-group\">\n"
"                    <label for=\"ssid\">WiFi名称 (SSID):</label>\n"
"                    <input type=\"text\" id=\"ssid\" name=\"ssid\" required>\n"
"                </div>\n"
"                <div class=\"form-group\">\n"
"                    <label for=\"password\">WiFi密码:</label>\n"
"                    <input type=\"password\" id=\"password\" name=\"password\">\n"
"                </div>\n"
"                <button type=\"submit\">连接</button>\n"
"            </form>\n"
"            <div id=\"statusMessage\" class=\"status\"></div>\n"
"        </div>\n"
"        <div class=\"footer\">\n"
"            <p>© 2023 智能机器人系统 | 版本 1.0</p>\n"
"        </div>\n"
"    </div>\n"
"    <script>\n"
"        document.addEventListener('DOMContentLoaded', function() {\n"
"            const form = document.getElementById('wifiForm');\n"
"            const statusMessage = document.getElementById('statusMessage');\n"
"            const networkList = document.getElementById('networkList');\n"
"            \n"
"            // 模拟获取网络列表\n"
"            setTimeout(function() {\n"
"                const networks = [\n"
"                    { ssid: 'HomeWiFi', signal: '强' },\n"
"                    { ssid: 'Office_Network', signal: '中' },\n"
"                    { ssid: 'Guest_WiFi', signal: '弱' },\n"
"                    { ssid: 'IoT_Network', signal: '强' }\n"
"                ];\n"
"                \n"
"                networkList.innerHTML = '';\n"
"                networks.forEach(function(network) {\n"
"                    const item = document.createElement('div');\n"
"                    item.className = 'network-item';\n"
"                    item.innerHTML = network.ssid + \n"
"                        '<span class=\"signal-strength\">信号: ' + network.signal + '</span>';\n"
"                    item.addEventListener('click', function() {\n"
"                        document.getElementById('ssid').value = network.ssid;\n"
"                    });\n"
"                    networkList.appendChild(item);\n"
"                });\n"
"            }, 1500);\n"
"            \n"
"            form.addEventListener('submit', function(e) {\n"
"                e.preventDefault();\n"
"                \n"
"                const ssid = document.getElementById('ssid').value;\n"
"                const password = document.getElementById('password').value;\n"
"                \n"
"                if (!ssid) {\n"
"                    showStatus('请输入WiFi名称', 'error');\n"
"                    return;\n"
"                }\n"
"                \n"
"                showStatus('正在连接到 ' + ssid + '...', 'connecting');\n"
"                \n"
"                // 发送配置到ESP32\n"
"                fetch('/connect', {\n"
"                    method: 'POST',\n"
"                    headers: {\n"
"                        'Content-Type': 'application/json',\n"
"                    },\n"
"                    body: JSON.stringify({\n"
"                        ssid: ssid,\n"
"                        password: password\n"
"                    })\n"
"                })\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        showStatus('连接成功! 设备正在重启...', 'success');\n"
"                        setTimeout(function() {\n"
"                            window.location.href = '/';\n"
"                        }, 5000);\n"
"                    } else {\n"
"                        showStatus('连接失败: ' + data.message, 'error');\n"
"                    }\n"
"                })\n"
"                .catch(error => {\n"
"                    showStatus('连接请求失败，请重试', 'error');\n"
"                    console.error('Error:', error);\n"
"                });\n"
"            });\n"
"            \n"
"            function showStatus(message, type) {\n"
"                statusMessage.textContent = message;\n"
"                statusMessage.className = 'status ' + type;\n"
"            }\n"
"        });\n"
"    </script>\n"
"</body>\n"
"</html>";

// 连接成功页面的HTML代码
const char* wifi_success_html = "<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>WiFi连接成功</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            background-color: #f5f5f5;\n"
"            color: #333;\n"
"        }\n"
"        .container {\n"
"            max-width: 400px;\n"
"            margin: 0 auto;\n"
"            padding: 20px;\n"
"        }\n"
"        .header {\n"
"            text-align: center;\n"
"            padding: 20px 0;\n"
"            background-color: #28a745;\n"
"            color: white;\n"
"            border-radius: 5px 5px 0 0;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        .content {\n"
"            background-color: white;\n"
"            border-radius: 5px;\n"
"            padding: 20px;\n"
"            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n"
"            text-align: center;\n"
"        }\n"
"        .success-icon {\n"
"            font-size: 48px;\n"
"            color: #28a745;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        .info {\n"
"            margin: 20px 0;\n"
"            padding: 15px;\n"
"            background-color: #f8f9fa;\n"
"            border-radius: 4px;\n"
"            text-align: left;\n"
"        }\n"
"        .info p {\n"
"            margin: 5px 0;\n"
"        }\n"
"        .footer {\n"
"            text-align: center;\n"
"            margin-top: 20px;\n"
"            color: #666;\n"
"            font-size: 12px;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <div class=\"header\">\n"
"            <h1>WiFi连接成功</h1>\n"
"        </div>\n"
"        <div class=\"content\">\n"
"            <div class=\"success-icon\">✓</div>\n"
"            <h2>设备已成功连接到WiFi网络</h2>\n"
"            <p>您的智能机器人现在已连接到互联网。</p>\n"
"            <div class=\"info\">\n"
"                <p><strong>网络名称:</strong> <span id=\"ssid\">%SSID%</span></p>\n"
"                <p><strong>IP地址:</strong> <span id=\"ip\">%IP%</span></p>\n"
"                <p><strong>信号强度:</strong> <span id=\"signal\">%SIGNAL%</span></p>\n"
"            </div>\n"
"            <p>设备将在几秒钟后自动重启并应用新的网络设置。</p>\n"
"        </div>\n"
"        <div class=\"footer\">\n"
"            <p>© 2023 智能机器人系统 | 版本 1.0</p>\n"
"        </div>\n"
"    </div>\n"
"    <script>\n"
"        // 自动刷新页面计时器\n"
"        let countdown = 10;\n"
"        const interval = setInterval(function() {\n"
"            countdown--;\n"
"            if (countdown <= 0) {\n"
"                clearInterval(interval);\n"
"                window.location.href = '/';\n"
"            }\n"
"        }, 1000);\n"
"    </script>\n"
"</body>\n"
"</html>";

#endif /* __HTML_DATA_H */ 